### ISSUE TITLE
Passing an object along to onSelect

### ISSUE THREAD

**Issue by kneeki** [bassjobsen/Bootstrap-3-Typeahead#104]
Hey all, I'm having trouble figuring out how I should be passing along an object of anything more than the default to onSelect for more extensive usage. Here's my code, any help would be greatly appreciated!

```
$("input[type='text']").typeahead({
	onSelect: function(item) {
		// Do things with the item object here.
	},
	items: 10,
	ajax: {
		url: "modules/scripts/Search.php",
		timeout: 500,
		triggerLength: 1,
		method: "POST",
		preDispatch: function (str) {
			return {
				String: str,
				State: $("#"+$("#"+InputBox).attr("data-place")+"StateText").attr("data-sc")
			}
		},
		preProcess: function (data) {
			if (data.success === false) { return false; }
			// I think I'd create the item object here, or pass it along?
			
			var DD = [];
			$.each(data, function(key, value) {
				DD.push(value['City']+" - "+value['Zip']);
				TempArr[value['ID']] = data[key];
			});
			
			return DD;
		}
	}
});

**Comment by bassjobsen** [comment]
Please take a look at https://github.com/bassjobsen/Bootstrap-3-Typeahead#javascript-example.
Typeahead does not provide you an ajax function. You should use the method mentioned already, or define your source as an function:

```javascript
source: function(query) {//should return a json object}
```
In both situations your source should return a array of strings, an array of JSON objects with a name property. See also: https://github.com/bassjobsen/Bootstrap-3-Typeahead#using-json-objects-instead-of-simple-strings

You should also use `afterSelect` in stead of `onSelect`. Hope this helps??
