### ISSUE TITLE
Display HTML

### ISSUE THREAD

**Issue by jaschweder** [bassjobsen/Bootstrap-3-Typeahead#113]
Hi, is there some way to display html in place of display only text ? for example if I want to display a icon of fontawesome on the display of the source.

**Comment by MissChocoe** [comment]
You will have to give a render method in your configuration. Copy the original code and then modify it to add any element you want.

**Comment by A----** [comment]
It's the `highlighter` function that converts it to text so you can override it in your configuration.

Here's an implementation:
```javascript
$('#testcase').typeahead({
[…]
	displayText: function (item) {
		return item.name + " &ndash; " + item.type + ' <i class="fa fa-glass"></i>';
	},
	highlighter: function(item) {
		var query = this.query;
		if(!query) {
			return '<div> ' + item + '</div>';
		}
					
		var reEscQuery = query.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
		var reQuery = new RegExp('(' + reEscQuery + ')', "gi");
					
		var jElem = $('<div></div>').html(item);
		var textNodes = $(jElem.find('*')).add(jElem).contents().filter(function () { return this.nodeType === 3; });
		textNodes.replaceWith(function() {
			return $(this).text().replace(reQuery, '<strong>$1</strong>')
		});
					
		return jElem.html();
	}
[…]
});
```

**Comment by okdewit** [comment]
@A---- : Thanks, your snippet is pretty useful.

It seems like when I press enter/click on the highlighted item, the HTML is parsed (as plaintext) into the input box though, which is less desirable.

**Comment by A----** [comment]
I should have done a jsFiddle, I'm quite sure it worked in my case.

If you can spare the time, can you do one? Maybe I (or someone else) can help you.

**Comment by okdewit** [comment]
Solved it by adding the afterSelect callback function in the option hash:

    afterSelect: function( item ){
        $('.typeahead').val( item.product );
    },

(with product being the main "label" in the prefetched json)
Feels a bit dirty overwriting the value manually like this, but it works well.

**Comment by gegham-khachatryan** [comment]
https://jsfiddle.net/geghamk/59eranrc/2/
