### ISSUE TITLE
Touch Devices not working

### ISSUE THREAD

**Issue by JAKgit** [bassjobsen/Bootstrap-3-Typeahead#121]
On touch devices the typeahead does not work it always selects the first one instead of the touched one.

Could not find a solution, thank you for your help.

**Comment by JAKgithub** [comment]
Ok, I found the solution.

listen: function () {
    
      this.$element
        .on('focus',    $.proxy(this.focus, this))
        .on('blur',     $.proxy(this.blur, this))
        .on('keypress', $.proxy(this.keypress, this))
        .on('keyup',    $.proxy(this.keyup, this));

      if (this.eventSupported('keydown')) {
        this.$element.on('keydown', $.proxy(this.keydown, this));
      }
      
      var isTouchDevice = 'ontouchstart' in document.documentElement;
      
      if (isTouchDevice) {
      
      	this.$menu.on('touchstart', 'li', $.proxy(this.touchstart, this)).on('touchend', $.proxy(this.click, this));
      
      } else {
      	
      	this.$menu
      	  .on('click', $.proxy(this.click, this))
      	  .on('mouseenter', 'li', $.proxy(this.mouseenter, this))
      	  .on('mouseleave', 'li', $.proxy(this.mouseleave, this));
      }
    },

plus some extra code:

touchstart: function(e) {
    	e.preventDefault();
    	this.$menu.find('.active').removeClass('active');
    	$(e.currentTarget).addClass('active');
    },
    
    touchend: function(e) {
    	e.preventDefault();
    	this.select();
    	this.$element.focus();
    },

**Comment by grokcode** [comment]
I'm also seeing this issue on an iOS device (both Chrome and Safari), but wasn't able to reproduce on android.
