### ISSUE TITLE
!!!!!!!!!!!!!!!!!!!! Please remove this post !!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Ottiko** [bassjobsen/Bootstrap-3-Typeahead#153]
!!!!!!!!!!!!!!!!!!!! Please remove this post !!!!!!!!!!!!!!!!!!!!

**Comment by Ottiko** [comment]
???

**Comment by patelnav** [comment]
Look at the afterSelect option. It gets called when you select an item in the list

**Comment by Ottiko** [comment]
Ok, but how I can to add addition param to my <li> option? exp. data-id
