### ISSUE TITLE
Only one query

### ISSUE THREAD

**Issue by Ottiko** [bassjobsen/Bootstrap-3-Typeahead#157]
I have JS function which return countries list.
```
		function GetCountries(countryId) {
			$.ajax({
				type: 'GET',
				url: "../GetCountries",
				data: {
					countryId: countryId
				},
				success: function (result) {
					// console.log("GetCountries");
					// console.log(result);
				}
			});
		}
```

Now I want to call this function from ***.typeahead*** only one, and when filter return function data.

I try this code, but query is work always, when I press any key... :(
```
		$('input[name=country_title]').typeahead({
			minLength: 1,
			items: 2000,
			source: function(query, process) {
				var result = null;
				$.ajax({
					url: ".../GetCountries",
					type: "GET",
					dataType: "JSON",
					async: false,
					success: function(result) {
						objects = [];
						map = {};
						$.each(result, function(i, object) {
							map[object.caption.en] = object;
							objects.push(object.caption.en);
						});
						process(objects);
					} 
				});
			},
			afterSelect: function (item) {
				// Call function
				var countryId = map[item].Id;
				GetConsulates(countryId, null);
			}
		});
```

**Comment by gpetrioli** [comment]
If you want to do it only once, then run it the other way around.

First get the data and then initialize the plugin with that source..

	$.ajax({
		url: ".../GetCountries",
		type: "GET",
		dataType: "JSON",
		async: false,
		success: function(result) {
			objects = [];
			map = {};
			$.each(result, function(i, object) {
				map[object.caption.en] = object;
				objects.push(object.caption.en);
			});

			 $('input[name=country_title]').typeahead({
				minLength: 1,
				items: 2000,
				source: objects,
				afterSelect: function (item) {
					// Call function
					var countryId = map[item].Id;
					GetConsulates(countryId, null);
				}
			});
		} 
	});

**Comment by Ottiko** [comment]
Respect, Thx.

**Comment by Ottiko** [comment]
If user write text which not found, how I can show this panel http://i.imgur.com/IdMKdgE.png

**Comment by Ottiko** [comment]
Please help me...

**Comment by Ottiko** [comment]
Please help me...

**Comment by gpetrioli** [comment]
@Ottiko the link you posted is what you want for the `typeahead` initialization. (*you need to use the `sorter`, `highlighter` and `updater` options*)

**Comment by Ottiko** [comment]
Ok, but "afterSelect" I must replace with "updater" option?

**Comment by gpetrioli** [comment]
@Ottiko, you can do that yes.
