### ISSUE TITLE
Typeahead replacement

### ISSUE THREAD

**Issue by ZacheryPD** [bassjobsen/Bootstrap-3-Typeahead#160]
I need to do a master detail box where the detail re-queries it's results when the master changes. 

The code works beautifully the first time it's run, but any subsequent calls to element.typeahead({ source }) doesn't do anything. No error, no visual clutching, it just doesn't change the source for autocomplete.

**Comment by Malavos** [comment]
Could you provide your code?

**Comment by ZacheryPD** [comment]
I wound up going with a different solution and no longer have the code.  I'll remove the issue since I can no longer provide useful updates.

**Comment by neoadventist** [comment]
I'm experiencing the same thing, how do I supply new data to the typeahead?

**Comment by ZacheryPD** [comment]
I was not able to accomplish this with Bootstrap's typeahead but I hacked https://twitter.github.io/typeahead.js/ to do it fairly easily. I can't remember how I hacked it anymore, and the code was for a client so I no longer have it,  but I hope that direction helps. 

I am not convinced that this can't be done with Bootstrap, but I failed to do so before the deadline.
