### ISSUE TITLE
Typeahead doesn't work on iOS 9

### ISSUE THREAD

**Issue by fanmusic** [bassjobsen/Bootstrap-3-Typeahead#161]
After upgrading my iPad Air 2 to iOS 9, the typeahead feature doesn't work any more. Does anyone have the same issue?
I'm using version 3.0.3 but the latest version still doesn't work

**Comment by mdumic** [comment]
@fanmusic What is your setup? External keyboard maybe?

**Comment by fanmusic** [comment]
@mdumic no I didn't use any further setup. I just used Safari browser on my iPad Air 2(iOS 9) as usual.
Can you show me a demo page so that I can verify again?
Thanks.

**Comment by fanmusic** [comment]
@mdumic it doesn't work when I use external source(call ajax to get data). When I use static data, I can see the autosuggestion list but when I input some characters to the textbox, the result stays the same, it doesn't match with the keyword I typed.

**Comment by Malavos** [comment]
@fanmusic could you provide a screenshot?

**Comment by fanmusic** [comment]
@Malavos iOS9 doesn't support keyup event. I have a work around to fix this. Thanks.

By the way, in my previous comment I already said that the typeahead doesn't work on iOS9, I don't know how to give you a screenshot to explain it's not working :)
