### ISSUE TITLE
Npm release

### ISSUE THREAD

**Issue by megapctr** [bassjobsen/Bootstrap-3-Typeahead#171]
There's no bootstrap-3-typeahead package on npm. Are you planning on a release soon?

**Comment by bassjobsen** [comment]
Thanks for your message. Np, i Will release it today
Op 7 dec. 2015 11:43 AM schreef "Filip" <notifications@github.com>:

**Comment by bassjobsen** [comment]
See: https://www.npmjs.com/package/bootstrap-3-typeahead
