### ISSUE TITLE
Use id value

### ISSUE THREAD

**Issue by albertocepeda** [bassjobsen/Bootstrap-3-Typeahead#173]
Is there a way to show the value of name and save the id value in an hidden input
i try something like this:

HTML:

`<input type="text" class="form-control thUsuario typeahead" placeholder="Usuario..." id="usuario" name="usuario" autocomplete="off" data-provide="typeahead">`
`<input type="hidden" id="hdnUsuario" name="hdnUsuario" value="<%=idUsuario%>"/>`

Script:
var $input = $('#usuario');
    $input.typeahead({
        name: 'Usuario',
        displayKey: 'id',
        source: [
            { id: "1", name: "Pablo" },
            { id: "2", name: "Pedro" },
            { id: "3", name: "Pietro" },
            { id: "4", name: "Portes" },
            { id: "4", name: "Puente" }
        ],
            autoSelect: true
    })
    .on('typeahead:selected', function ($e, item) {
        $("#hdnUsuario").val(item.id);
    })

Thanks for your time

**Comment by yaya-git** [comment]
Can you try this, option:

                    
                    $input.typeahead({source: response
                        , autoSelect: true
                        , updater: function (item) {
                            return item;
                        }
                        , afterSelect: function (item) {
                            console.log('afterSelect: ' + item.id);
                            $('#inputtypeHidden').val(item.id);
                        }
                    });

**Comment by marcelo2605** [comment]
I'm using mutiple inputs with typeahead in the same page. So my selector inside afterSelect function is a class.

But how can I select the current input?
