### ISSUE TITLE
Spurious menu show with showHintOnFocus

### ISSUE THREAD

**Issue by tobia** [bassjobsen/Bootstrap-3-Typeahead#176]
With **showHintOnFocus** enabled, after selecting an item the menu is shown again.

This is due to the following line, that I suggest disabling when showHintOnFocus:

    click: function (e) {
        e.preventDefault();
        this.select();
        this.$element.focus();  // wrong if showHintOnFocus!
    },

**Comment by JakubKahovec** [comment]
+1
