### ISSUE TITLE
issue with data-source attribute

### ISSUE THREAD

**Issue by neptunecentury** [bassjobsen/Bootstrap-3-Typeahead#18]
When using the data-source attribute,  typeahead takes it as a literal source.

example
<input type="text" id="tags" class="form-control" data-provide="typeahead" data-source="getData" />

<script>
function getData(query, process)
        {
            //debugger;
            return ['test', 'abc', 'super'];
        }
</script>

as I type, I will get single letters, 'g' 'e' 't', etc... because it isn't looking at the defined getData function, but instead, using the string as the source.

it works fine if I use:
$('#tags').typeahead({ source: getData });

**Comment by ss89** [comment]
Using the data-source attribute on an input doesn't work.
That is what @neptunecentury wanted to tell.
I just tried that myself with 4.0.0 and have the same problem.
Using the JavaScript snippet to initialize it with a source property works though.

**Comment by neptunecentury** [comment]
I completely forgot about this. Yes, I did mean that the attribute doesn't work, but when initialized in script it does.
