### ISSUE TITLE
dynamic addItem

### ISSUE THREAD

**Issue by RWOverdijk** [bassjobsen/Bootstrap-3-Typeahead#201]
Hey, cool project.

Quick question.. I want to add a button to the end of the list (addItem), something like:

`+ Create venue "User input here"`

It's a, _lookup or create_ kind of thing. Is this possible? I couldn't find it in the readme. I found `addItem` but that's a static value, and also doesn't contain an icon.

**Comment by RWOverdijk** [comment]
Bump

**Comment by schmijos** [comment]
What did you try with `addItem`?

**Comment by todvora** [comment]
Hi, I had similar requirement, hacked it by overriding the process function:

```js
 // hack typeahead, allow adding a last item constructed by free input
let oldProcess = $.fn.typeahead.Constructor.prototype.process;
$.fn.typeahead.Constructor.prototype.process = function (items) {
    if (this.options.freeInputItem) {
        const maxItemsDisplayed = this.options.items;
        items.splice(maxItemsDisplayed - 1, 0, this.options.freeInputItem());
    }
    return oldProcess.call(this, items);
};
```

Which introduces a new option `freeInputItem`, that can be defined as:

```
freeInputItem: () => {
    const value = $(el).val();
    return `Create venue "${value}"` ;
}
```

So the `addItem` is replaced by `freeInputItem` which is dynamic, may be constructed based on current entered value.

**Comment by fmquaglia** [comment]
@todvora you rock, my friend. Thanks a lot.
