### ISSUE TITLE
displayText weird

### ISSUE THREAD

**Issue by gbaumgart** [bassjobsen/Bootstrap-3-Typeahead#202]
![image](https://cloud.githubusercontent.com/assets/1205100/13372641/581af216-dd4c-11e5-81e4-36cd852197b1.png)

after selecting, it shows the markup generated by displayText in the input text field. 
How to fix this?

`var substringMatcher = function(strs) {
                    return function findMatches(q, cb) {
                        var matches, substringRegex;

                        // an array that will be populated with substring matches
                        matches = [];

                        // regex used to determine if a string contains the substring `q`
                        substrRegex = new RegExp(q, 'i');

                        // iterate through the pool of strings and for any string that
                        // contains the substring `q`, add it to the `matches` array
                        $.each(strs, function(i, str) {
                            if (substrRegex.test(str)) {
                                matches.push(str);
                            }
                        });

                        cb(matches);
                    };
                };
                var states = [{"name":"Test","id":"1"},{"name":"Tom","id":"2"}];
                this.$input.typeahead({
                    hint: true,
                    highlight: true,
                    minLength: 1,
                    name: 'states',
                    showHintOnFocus:true,
                    source: substringMatcher(states),
                    highlighter: function(item)
                    {
                        return item;
                    },
                    displayText: function (item) {
                        return item.id + ' - ' + '<span class="text-info">'+item.name+'</span>';
                    }
                });`

**Comment by MissChocoe** [comment]
displayText is intended to have the raw text that should be used in the suggestion while user type, mainly if you want to use object as items and extract something else than the name (which is the default implementation). It is the text that is use to compare with the user typed text and it is also the text that is put in the input when user picks it. If you want to change the look in the menu, you need to change the render method.
