### ISSUE TITLE
Synchronize min file

### ISSUE THREAD

**Issue by JoniJnm** [bassjobsen/Bootstrap-3-Typeahead#206]
The min file isn't synchronized with no minimized file, so there isn't the same to use one or the other.

I think there are two options:

1. Create a develop branch where accept pull requests, without min file. Run grunt after merge with master.
2. No new branch. In master, always run grunt before push (or accept pull request from website)

**Comment by bassjobsen** [comment]
thanks! i have synchronized the min file now?
Did you mean i can automatically run grunt after each merge request?

**Comment by JoniJnm** [comment]
No, I mean that the min and non minimized files haven't always the same content, so when you use one or another could be differences.

So, I think, you should search for one way to avoid it and I proposed two.

**Comment by morpheus-87** [comment]
Unfortunately, it's again the same problem. When I'm using the "normal" file, everything works fine. When I use the minified version, I get an error:

`TypeError: d.replace is not a function`
