### ISSUE TITLE
Could you please force an update at packagist?

### ISSUE THREAD

**Issue by mrohnstock** [bassjobsen/Bootstrap-3-Typeahead#215]
https://packagist.org/packages/bassjobsen/bootstrap-3-typeahead

It still stuck at v4.0.0 :(. Thanks :)

**Comment by bassjobsen** [comment]
@mrohnstock i do not know how to do this, because of https://github.com/bassjobsen/Bootstrap-3-Typeahead/blob/master/composer.json does not contain version information?

**Comment by mrohnstock** [comment]
You just have to login to packagist.org, switch to your project and push the `Force Update`-Button. Packagist will use all your tags as versions automagically.

In general you can also add your packagist API Token to github, so github will automatically update the package at packagist, if something got commited here. More infos can be found [here](https://packagist.org/about#how-to-update-packages).

**Comment by bassjobsen** [comment]
@mrohnstock thanks for your explanation. I'm willing to at the hook for automatically updates, but as far as i do understand now; i'm not the own of the package on Packagist. It seems that @Guite owns the package, so he should create the hook or should transfer the ownership.

**Comment by Guite** [comment]
@bassjobsen added you as maintainer.

**Comment by bassjobsen** [comment]
@mrohnstock and @Guite thank you both. I have a the hook too now.
