### ISSUE TITLE
angular directive for bootstrap3-typeahead

### ISSUE THREAD

**Issue by davidkonrad** [bassjobsen/Bootstrap-3-Typeahead#216]
Hey @bassjobsen (and others) I am using `bootstrap3-typeahead` a lot, but is also using angular.  At some point the lack of a directive was a real pain, so I ended up making my own. It is very small and simple, but it support all options (as far as I have tested)  you can bind a `ng-model` to the typeahead, use `$scope` methods and use services as source. It also cleanup the typeahead instance. 

https://github.com/davidkonrad/angular-bootstrap3-typeahead

**Comment by bassjobsen** [comment]
@davidkonrad, thanks you; i've add a link to your directive to the README
