### ISSUE TITLE
remote option not showing dropdown box

### ISSUE THREAD

**Issue by davidtzoor** [bassjobsen/Bootstrap-3-Typeahead#218]
I have a typeahead object which works great with the prefetch option, but the remote option is not working properly. I get the response back (which is a simple array of strings) but I don't see the dropdown box.
Here is my code:

```
var queries = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.whitespace,
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                prefetch: {
                    url: "/static/assets/data/queries.json",
                    cache: false
                },
                remote: {
                    url: '/search/suggestions/q=%QUERY',
                    wildcard: '%QUERY'
                }
            });

            element.typeahead({
                source: queries.ttAdapter(),
                autoSelect: false,
                // //afterSelect: scope.searchCtrl.search,
                showHintOnFocus: true
            });
```

Any idea what's the issue?

**Comment by chlab** [comment]
I have the same problem. I built my testcase with the original typeahead and bloodhound and everything works. Now I replaced typeahead with bootstrap-3-typeahead to get bootstrap integration and it's not working anymore.

This is what my code looks like:

	var fbApi = new Bloodhound({
		datumTokenizer: Bloodhound.tokenizers.whitespace('name'),
		queryTokenizer: Bloodhound.tokenizers.whitespace,
		remote: {
			wildcard: 'QUERY',
			url: 'https://graph.facebook.com/v2.6/search?' + $.param(params),
			transform: function(response) {
				return _.filter(response.data, function(place) {
					return _.contains(categories, place.category);
				});
			}
		}
	});
	fbApi.initialize();

	$(this.refs.restaurant).typeahead(
		{
		minLength: 3,
		source: fbApi.ttAdapter()
		});

If I put a `console.log()` in the the transform function, I can see that it's processing the data correctly. It's just that nothing is being shown.

**Comment by yasunariw** [comment]
I have the same problem. I'm getting the data remotely with AJAX. Like chlab, `console.log(data)` shows that the query is running properly and data is retrieved correctly - the final result doesn't show up.

[Here's my thread on stackoverflow (so far no luck)](http://stackoverflow.com/questions/36758653/typeahead-bootstrap-no-dropdown-shows-for-ajax-calls)

[Also relevant question](http://stackoverflow.com/questions/22983665/twitter-bootstrap-3-0-typeahead-ajax-example)

**Comment by chlab** [comment]
I switched back to typeahead and dropped in the styles from [here](https://github.com/bassjobsen/typeahead.js-bootstrap-css). Seems to work.

**Comment by bassjobsen** [comment]
@yasunariw also see: http://w3masters.nl/Bootstrap-3-Typeahead/json.html i think i works as expected

**Comment by bassjobsen** [comment]
@davidtzoor  and @chlab 

It works with local data, so it seems your issues are related to bloodhound?

    // instantiate the bloodhound suggestion engine
    var bloodhound = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.whitespace,
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    local:  ["(A)labama","Alaska","Arizona","Arkansas","Arkansas2","Barkansas"]
    });    
    // initialize the bloodhound suggestion engine
    bloodhound.initialize();
    $('.typeahead').typeahead(
    {
    items: 4,
    source: bloodhound.ttAdapter()  
    });

**Comment by davidtzoor** [comment]
Prefetch and local are working properly. The issue is with remote which doesn't show the results. 
The interaction with the remote server is working properly and the response is coming back, but the suggestion menu is not showing.

**Comment by bassjobsen** [comment]
@davidtzoor well i see now. `remote` does not work indeed, possible because of the results load asynchrony? also see: https://github.com/twitter/typeahead.js/issues/1407

**Comment by yasunariw** [comment]
@bassjobsen Thank you. I will get back to you when I make some progress.

**Comment by luisepbueno** [comment]
That happens because Bloodhound expects Typeahead source function to receive three parameters: query, sync and async. But actually Bootstrap 3 Typeahead source functions works with only two parameters: query and process.

Look for 

`this.source(this.query, $.proxy(this.process, this));`

and replace with

`this.source(this.query, null, $.proxy(this.process, this));`

That's just a workaround and not a fix.

**Comment by legionio** [comment]
So is there a fix for this? I have the same problem

**Comment by xhaggi** [comment]
Hope #271 will fix your issues with bloodhound getting its data from a remote source.

**Comment by roddydairion** [comment]
This is how I use remote bloodhound and typeahead. 
```
// Instantiate the Bloodhound suggestion engine
var movies = new Bloodhound({
    datumTokenizer: function (datum) {
        return Bloodhound.tokenizers.whitespace(datum.value);
    },
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {
        url: 'http://api.themoviedb.org/3/search/movie?query=%QUERY&api_key=f22e6ce68f5e5002e71c20bcba477e7d',
        filter: function (movies) {
            return movies.results;
        }
    }
});

// Initialize the Bloodhound suggestion engine
movies.initialize();

// Instantiate the Typeahead UI
$('.typeahead').typeahead(null, {
    displayKey: function (suggestion){
    	return suggestion.title
    },
    source: movies.ttAdapter()
});
```
Original code from [http://jsfiddle.net/Fresh/UkB7u/](url)
