### ISSUE TITLE
A click causes multiple selections (Chrome and Firefox)

### ISSUE THREAD

**Issue by odan** [bassjobsen/Bootstrap-3-Typeahead#282]
Hello!

I think there is a bug. If I click at the item with the mouse **two** items are selected.
The expected result: Only one selected item.
This bug occurs only in firefox and chrome, but not in IE 11.

I have noticed, that there are too many event handlers registerd for the menu which causes this issue. 

https://github.com/bassjobsen/Bootstrap-3-Typeahead/blob/master/bootstrap3-typeahead.js#L372

If you remove these lines it will work (in all browsers)
![image](https://cloud.githubusercontent.com/assets/781074/25613346/2d043170-2f2e-11e7-8ea4-3ff4d50d51b4.png)

Edit: Added a workaround

```js
var typeahead = $('#search').data('typeahead');
$(typeahead.$menu).off('mouseenter mouseleave mousedown');
```

**Comment by bassjobsen** [comment]
Hi @odan thanks.
What about the workaround? Is it required too?

**Comment by odan** [comment]
Hi @bassjobsen This workaround is not required.
