### ISSUE TITLE
typeerror typeahead.process is not a function

### ISSUE THREAD

**Issue by amarpreetsaini** [bassjobsen/Bootstrap-3-Typeahead#40]
typeahead: {
I am using this typehead with bootstrap tagsinput. I am getting " typeerror typeahead.process is not a function " error when i query .
$('#mystuff_tag_box').tagsinput({
 typeahead: {
source: function (query, process) {
    return $.getJSON(
        '{% url "autocomplete_tag" %}',
        { term: query },
        function (data) {
            return process(data);
        });
},
})

If i try only typeahead then it works fine. But does not work with bootstrap tagsinput.

**Comment by nicolastrenti** [comment]
Hi everyone,

I'm trying to use Bootstrap 3 Typeahead and Bootstrap tags input together, with an external source of data.
This code works perfect for me:

    jQuery('#tag_field').tagsinput({typeahead :
    {
    source: ["Alabama","Alaska","Arizona","Arkansas","California"]
    }
    });

But when I try to use a dynamic remote URL, it doesn't work anymore. My JS code is now:

    jQuery('#tag_field').tagsinput({typeahead :
    {
    source: function (query) {
       return jQuery.get('tagsearch.php?query=' + query);
    }
    }
    });

My remote URL is a PHP file with a MySQL query, which returns a json encoded array, with the exact same syntax as the above source, for example the result of _tagsearch.php?query=tag_ is:

    ["tag1","tag2","tag3"]

But when I use this code, here is the result:

![image](https://cloud.githubusercontent.com/assets/1919354/5595964/6d83bbae-9281-11e4-8c49-ca95edea33b0.png)

Could anyone please help me ? I can't undestand what is wrong... Thanks !

**Comment by nicolastrenti** [comment]
Ok, I figure it out. The return of my PHP file wasn't considered as a json. I had to add _items = JSON.parse(items);_ in the processItems function in Bootstrap tagsinput's source function:

    function processItems(items) {
    var texts = [];
    items = JSON.parse(items);
    for (var i = 0; i < items.length; i++) {
    var text = self.options.itemText(items[i]);
    console.log(text);
    map[text] = items[i];
    texts.push(text);
    }
    process(texts);
    }

I'm far from being an expert at Javascript, so I don't really understand why, but it works perfectly now. Sorry for that...

**Comment by tgely** [comment]
Hi @bassjobsen,
I found an issue with "." dot in source array. I have tried search for names.

Search code: "alu"

JSon source:
 ```php
{"0":"RB dark 7x16 alufelni","1":"Alufelni dekor\u00e1ci\u00f3s szalag 17col z\u00f6ld","2":"Alufelni dekor\u00e1ci\u00f3s szalag 17col s\u00e1rga","3":"Alufelni dekor\u00e1ci\u00f3s szalag 17col feh\u00e9r","4":"alufelni dekor\u00e1ci\u00f3s szalag 17col narancs","5":"Alufelni dekor\u00e1ci\u00f3s szalag 18col feh\u00e9r","6":"Alufelni dekor\u00e1ci\u00f3s szalag 18 col z\u00f6ld","7":"Alufelni dekor\u00e1ci\u00f3s szalag 18 col s\u00e1rga","8":"Alufelni dekor\u00e1ci\u00f3s szalag 18 col narancs","9":"Alufelni dekor\u00e1ci\u00f3s szalag 19 col z\u00f6ld","10":"Alufelni dekor\u00e1ci\u00f3s szalag 19 col narancs","11":"alufelni dekor\u00e1ci\u00f3s szalag 19 col s\u00e1rga","12":"Alufelni dekor\u00e1ci\u00f3s szalag 19 col feh\u00e9r","13":"H 6.5x15 alufelni","14":"Felni kupak D2 univerz\u00e1lis alufelni","15":"AirBlade 7.5x16 alufelni","19":"AirBlade 8x17 alufelni","26":"AirBlade 8x18 alufelni","32":"Antigua 8x18 alufelni","35":"Antigua 8.5x19 alufelni","39":"Antigua 9.5x19 alufelni","44":"Antigua 8.5x20 alufelni","47":"Antigua 9.5x20 alufelni","49":"Antigua dark 8x18 alufelni","52":"Antigua dark 8.5x19 alufelni","56":"Antigua dark 9.5x19 alufelni","61":"Antigua dark 8.5x20 alufelni","64":"Antigua dark 9.5x20 alufelni","66":"Intenso 6.5x15 alufelni","72":"Intenso 7x16 alufelni","78":"Intenso 7.5x17 alufelni","83":"Lascar 8x17 alufelni","90":"Lascar 8x18 alufelni","97":"Lascar 8.5x19 alufelni"}
```
If **"." dot** found in list item name like "Antigua 8.5x19 alufelni" the dropdown doesnt work. 
Any thoughts would be appreciated.

**Comment by jared-christensen** [comment]
@nicolastrenti 

This tripped me up too, you almost had it.

```javascript
source: function (query) {
    return jQuery.get('tagsearch.php?query=' + query, function(data){
        return process(data);
    });
}
```

**Comment by nicholasblexrud** [comment]
@jared-christensen, thanks for share your code. I was getting an error though saying that process was  undefined. Just included process as an argument, and viola!

`source: function (query) {
    return jQuery.get('tagsearch.php?query=' + query, function(data){
        return process(data);
    });
}`

**Comment by jared-christensen** [comment]
@nicholasblexrud Thanks, I left that off by mistake.

**Comment by krept** [comment]
@bassjobsen I'm having a couple issues.  
When I use with tagsinput, I'm getting "duplicate" completions: 
![image](https://cloud.githubusercontent.com/assets/3244900/6911789/6055dccc-d733-11e4-9b1c-710b70475cfc.png)

![image](https://cloud.githubusercontent.com/assets/3244900/6911736/9e13e4b0-d732-11e4-87b3-653c9f56596a.png)
I'm using bootstrap3-typeahead.js v3.1.0

This happens when hitting enter, tab, or clicking on the result.  It does not happen when I put a comma after the text, or if I change window focus, and come back to the window.  It seems to only happen when using the typeahead to complete a result.  I tested this with a static source (states), as well and I'm receiving the same problem.

Thanks for any advice.

**Comment by azuneca** [comment]
I use the script mentioned above but it always returns me the first suggestion from the array when I have more

**Comment by night1008** [comment]
I want to select by clicking on the trigger event, how can I do?

**Comment by csimpi** [comment]
My working example here (with bootstrap tagsinput+bootstrap typeahead)

If the first letter appears only than you can use that line from example:
JSON.parse(result);

Good luck!

<script>
$( document ).ready(function() {                                                    
    /**
     * Typeahead
     */
    var elt = $("#'.$vinput_id.'"); //tagsinput input
    elt.tagsinput({
        typeahead: {
            afterSelect: function(val) { this.$element.val(""); },
            source: function(query) {
                var result = null;
                $.ajax({
                   url: "URL/TO/JSON/SOURCE&term="+query,
                   type: "get",
                   dataType: "html",
                   async: false,
                   success: function(data) {
                       result = data;
                   } 
                });
                console.log(result);

                return  JSON.parse(result);
               
           }
        }
    });
});
</script>

**Comment by csimpi** [comment]
My working example here (with bootstrap tagsinput+bootstrap typeahead)

If the first letter appears only than you can use that line from example:
JSON.parse(result);

Good luck!
```javascript
<script>
$( document ).ready(function() {                                                    
    /**
     * Typeahead
     */
    var elt = $("#'.$vinput_id.'"); //tagsinput input
    elt.tagsinput({
        typeahead: {
            afterSelect: function(val) { this.$element.val(""); },
            source: function(query) {
                var result = null;
                $.ajax({
                   url: "URL/TO/JSON/SOURCE&term="+query,
                   type: "get",
                   dataType: "html",
                   async: false,
                   success: function(data) {
                       result = data;
                   } 
                });
                console.log(result);

                return  JSON.parse(result);
               
           }
        }
    });
});
</script>
```

**Comment by paulossm** [comment]
Hello,
I am using bootstrap3 tags input and typeahead.js and I'm getting some inconsistencies as shown in my following code:

// including scripts ....
/js/plugin/bootstrap-tags/bootstrap-tagsinput.js
/js/plugin/bootstrap-tags/plugin/bootstrap3-typeahead.js
// ....
<input id='tagsInput' type='text' class='form-control'>
// ....
$(document).ready(function(){
    $('#tagsInput').tagsinput({
        typeahead: {
          source: ['Amsterdam', 'Washington', 'Sydney', 'Beijing', 'Cairo', 'New York']
        }
    });
});

Well, it seems to work and when I type something, the suggestions appear, but when I press enter on one of them, the input creates 2 tags: one with my 'unfinished typing' and other with the suggestion chosen.

~ Sorry for my english... ~

**Comment by shadowfoxish** [comment]
@paulossm  I'm getting the same problem as well.

**Comment by KaraMovich** [comment]
Bootstrap-3-Typeahead don't work with bloodhound in case of remote url, I edited the line 136 :
if($.isFunction(this.source)) this.source(this.query, $.proxy(this.process, this));
to
if($.isFunction(this.source)) this.source(this.query, $.proxy(this.process, this), $.proxy(this.process, this));

**Comment by suwey** [comment]
@paulossm see https://github.com/bassjobsen/Bootstrap-3-Typeahead/issues/145, I edit the code add option.noPut to make typeahead wont copy value when use with tagsinput.

**Comment by ArtemPavlenko** [comment]
Hi guys.
There is a bug when you use showHintOnFocus: true.
After you select an element from dropdown it close and open again.
Library renew focus on input and it leads to open dropdown again.
I solved by deleting this.$element.focus(); in close function.

**Comment by FingersKey** [comment]
How to   choose first Item when user choose anything

**Comment by muisish** [comment]
Is it possible to add category? Here is the screenshot for what I meant. 
![search drop down mrmotivator zeplin](https://cloud.githubusercontent.com/assets/1879342/17425400/274d1f14-5af7-11e6-9c6a-03bb32a426b5.png)

**Comment by webofcherry** [comment]
Hey guys...
Can anyone tell me whats the problem in my code ?
I am using (Bootstrap3.js and bootstrap3-typeahead.js) and (bootstrap.css and typeaheadjs.css) and new version of jQuery
This is index.php file

<!DOCTYPE html>
<html>
<head>
	<title>Typeahead Practise</title>
	<link rel="stylesheet" type="text/css" href="bootstrap_with_typeaheadjs.css">
	
</head>
<body>
	<div class="well">
		<input id="typeahead" type="text" class="span3" autocomplete="off" data-provide="typeahead" />
	</div>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
	<script src="bootstrap_with_bs3typeahead.js"></script>
	<script>
		$(function() {
			$('#typeahead').typeahead({
				source: function(typeahead, query) {
					$.ajax({
						url: 'source.php',
						type: 'POST',
						data: 'query=' + query,
						dataType: 'JSON',
						async: false,
						success: function(data) {
							typeahead.process(data);
						}
					});
				}
			});
		});
	</script>
</body>

source.php

<?php

	if (isset($_POST['query'])) {
		
		define("DB_SERVER", "localhost");
		define("DB_USER", "root");
		define("DB_PASS", "");
		define("DB_NAME", "singapurelc");
		// 1 : Creating database connection
		
		$connection = mysqli_connect(DB_SERVER, DB_USER, DB_PASS, DB_NAME);

		//test if the error occured
		if(mysqli_connect_errno()) {

			die("Failed to connect with Database : " . mysqli_connect_error() . " ( " . mysqli_connect_errno() . " ) ");
		}

		$query = $_POST['query'];
		$array = array();
		$ready = "SELECT * FROM stock WHERE company LIKE '%($query)%'";
		$result = mysqli_query($connection, $ready);

		while ($row = mysqli_fetch_assoc($result)) {
			$array[] = $row['company'];
		}

		echo json_encode($array);
	}
?>

This error is occured in Mozillah Console when i type something in search field

" Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ jquery.min.js:4:15668
TypeError: typeahead.process is not a function "

**Comment by eddieace** [comment]
For some reason I get this error.

Uncaught ReferenceError: Bloodhound is not defined


any clues?

**Comment by zhuziqi227** [comment]
var $input = $("#typeahead");
$input.typeahead({
    source: function(query){
        var result =null;
        $.ajax({
            url: "/UserBlack/search?term="+query,
            type: "get",
            dataType: "html",
            async: false,
            success: function(data) {
                result = data;
            }
        });

        return  JSON.parse(result);
    },
    // autoSelect: true
});

Why I did not change after return page, AJAX is to get the data
@bassjobsen

**Comment by mekalasuraj** [comment]
I am having trouble integrating bootstrap 3 typeahead with tags input but
with objects as tags. It works if I use only tagsinput on input field, but
if I integrate it with typeahead then it doesn't work and I don't even get
any errors

   These are the modules i am using
   require('bootstrap-3-typeahead/bootstrap3-typeahead.min.js');
   require('bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js');
   require('bootstrap-tagsinput/dist/bootstrap-tagsinput.css');      

   $('#text').tagsinput({
   typeahead: {
   source: ['Alabama','Alaska','Arizona','Arkansas','California']
   }});

   <input type="text" class="form-control" name="test" 
   id="test" data-role="tagsinput" />

**Comment by webofCherry** [comment]
This may be help you out.
http://www.webofcherry.com/bootstrap-search-box/

**Comment by pannet1** [comment]
@bassjobsen 

first, please accept my congratulation for the awesome book on bootstrap.

i am trying to increase the list items of the bootstrap typeahead.

I made following attempts

1) changed the user javascript like so
`<script type="text/javascript">
	$('input.typeahead').typeahead({
	    source:  function (query, process) {
        return $.get('/myphplink', { query: query }, function (data) {
        		console.log(data);
        		data = $.parseJSON(data);
	            return process(data);
	        });
	    },
      minLength: 3,
      fitToElement: true,
      items: 15,			
     updater: function (item) {				
			}
	});`

2) changed the source bootstrap3-typeahead defauts

`Typeahead.defaults = {
    source: [],
    items: 15,    
  };`

But typeahead always returns only 10 items no matter what. Is this a bug or I am doing something wrong. Kindly help.

**Comment by mjbezer** [comment]
Hello, I need the element name: 'value' to autocomplete the input text 't03_name' and the code: 'value' element to autocomplete the hidden input 't03_idMember'. how to make?

HTML
`<input type="text" name="t03_nome" id="t03_nome" class="typeahead_3 form-control" autocomplete="off"/>
<input type="hidden" name="t03_idMembro" id="t03_idMembro" class="typeahead_3 form-control" />
`
JS
`$('.typeahead_3').typeahead({
 source: [
 {"name": "Evandro Luiz de Avila", "code": "4"},
 {"name": "Abedenego Sorence Borges", "code": "5"},
 {"name": "Nilza Marciano do Nascimento Borges", "code": "6"},
 ],
 autoSelect: true,
 });`

**Comment by seAfnan** [comment]
@mjbezer Maybe this can help u out
**HTML**
`<input type="text" id="search" name="search">`
**JS**
`var empData = [
    {
      "id": 1,
      "name": "FLETCHER"
    },
    {
      "id": 2,
      "name": "HARDY"
    },
    {
      "id": 3,
      "name": "EVANS"
    },
    {
      "id": 4,
      "name": "SOFIELD"
    },
    {
      "id": 5,
      "name": "PARKER"
    }
  ];`
Use:
`
$('#search').typeahead({

    name: 'employees',
    limit: 10,
    minLength: 1,
    source: function (query, process) {
      employees = [];
      map = {};
        $.each(empData, function (i, employee) {
          map[employee.name] = employee;
          employees.push(employee.name);
        });
      process(employees);
    },
    afterSelect: function(name) {
      alert(name)
    }
  })`
`
Please change the names by your own.

**Comment by jjasoncool** [comment]
`        $('#tagsinput').tagsinput({
            tagClass: 'badge-info',
            itemValue: 'id',
            itemText: 'name',
            freeInput: false,
            typeahead: {
                displayKey: 'name',
                afterSelect: function (item) {
                    // 此plugin的物件需要使用this.$element才抓的到
                    $(this.$element).val("");
                },
                source: function(query) {
                    params.set("action", "upload");
                    return $.ajax({
                        url: "./?" + params.toString(),
                        method: "POST",
                        data: {query: query, page: "searchList"},
                    });
                }
            }
		});`

**Comment by jjasoncool** [comment]
I use 
[bootstrap-typeahead.js](https://github.com/bassjobsen/Bootstrap-3-Typeahead) version 4.0.2
[bootstrap-tagsinput.js](https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/)  version 0.8.0
jquery v3.4.1
bootstrap v4.4

I try 3hours, the trick is typehead source need return **ajax object**.
below is my work source code.
Hope this information is helpful.
```javascirpt
$('#tagsinput').tagsinput({
    tagClass: 'badge-info',
    itemValue: 'id',
    itemText: 'name',
    freeInput: false,
    typeahead: {
        displayKey: 'name',
        afterSelect: function (item) {
            $(this.$element).val("");
        },
        source: function(query) {
            params.set("action", "upload");
            return $.ajax({
                url: "./?" + params.toString(),
                method: "POST",
                data: {query: query, page: "searchList"},
            });
        }
    }
});
```
