### ISSUE TITLE
Unbind keypress,keydown, keyup on typeahead("destroy");

### ISSUE THREAD

**Issue by konstantinkrassmann** [bassjobsen/Bootstrap-3-Typeahead#59]
In line 244 you do unbind your listeners with `.off`.
This causes to unbind even the custom listeners i place outside the typeahead. 

Use `.unbind("keypress", this.fnKeyPress);` instead to just unbind the plugins listeners.

``` javascript
// line 225
, listen: function(){
 this.fnKeyPress = $.proxy(this.fnKeypress, this);
 this.$element.on("keypress", this.fnKeyPress);
}
[...]
// line 244
.off('focus')
        .off('blur')
        .unbind('keypress', this.fnKeyPress)
        .off('keyup');
```

**Comment by mmoreram** [comment]
2,5 years later...

@bassjobsen did you understand the problem?
Using "destroy", nowadays, means removing all element binds outside this library, and of course, this is not a good solution at all.

**Comment by mmoreram** [comment]
@konstantinkrassmann Thanks. It works perfectly using unbind :)
