### ISSUE TITLE
'delay' option not documented

### ISSUE THREAD

**Issue by sebthebert** [bassjobsen/Bootstrap-3-Typeahead#62]
You should add the 'delay' option in your documentation

**Comment by hrj** [comment]
Seems to be documented now. This issue can be closed @bassjobsen

**Comment by sebthebert** [comment]
Thanks ! :)

**Comment by blckshrk** [comment]
hey!

The unit of the delay is missing. Is it milliseconds ? This should also be documented imho :-)

Thanks
