### ISSUE TITLE
not clear how to include bloodhound

### ISSUE THREAD

**Issue by sathia-musso** [bassjobsen/Bootstrap-3-Typeahead#90]
Hi, I need to use the remote method and I've read about the bloodhound extension. 
Although it is not  clear to me how to include it, should I include _all_ the typeahead js files?

if I load only the files inside this directory: 
./bower_components/typeahead.js/src/bloodhound/*.js 

i get: Uncaught ReferenceError: _ is not defined

**Comment by Dharmaitadmin** [comment]
@bassjobsen yes
